# Generated by Django 4.2.23 on 2025-06-27 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_teacher_account_student'),
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام رشته تحصیلی')),
            ],
        ),
        migrations.AlterField(
            model_name='classroom',
            name='grade',
            field=models.CharField(choices=[('first_grade', 'اول دبستان'), ('second_grade', 'دوم دبستان'), ('third_grade', 'سوم دبستان'), ('fourth_grade', 'چهارم دبستان'), ('fifth_grade', 'پنجم دبستان'), ('sixth_grade', 'ششم دبستان'), ('seventh_grade', 'هفتم متوسطه اول'), ('eighth_grade', 'هشتم متوسطه اول'), ('ninth_grade', 'نهم متوسطه اول'), ('tenth_grade', 'دهم متوسطه دوم'), ('eleventh_grade', 'یازدهم متوسطه دوم'), ('twelfth_grade', 'دوازدهم متوسطه دوم'), ('bachelor', 'کارشناسی'), ('master', 'کارشناسی ارشد'), ('phd', 'دکترا')], max_length=30, verbose_name='پایه تحصیلی'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='core.teacher', verbose_name='استاد'),
        ),
        migrations.CreateModel(
            name='StudentClassroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_classroom', to='exam.classroom', verbose_name='کلاس')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_classroom', to='core.student', verbose_name='دانشجو')),
            ],
        ),
    ]
