# Generated by Django 4.2.23 on 2025-07-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_major_alter_classroom_grade_alter_classroom_teacher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی آزمون',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای آزمون',
            },
        ),
    ]
