# Generated by Django 4.2.23 on 2025-07-04 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_customuser_is_team'),
        ('exam', '0004_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='متن گزینه')),
                ('is_correct', models.BooleanField(default=False, verbose_name='گزینه صحیح')),
            ],
            options={
                'verbose_name': 'گزینه',
                'verbose_name_plural': 'گزینه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن سوال')),
                ('question_type', models.CharField(choices=[('MultipleChoice', 'چندگزینه\u200cای'), ('Descriptive', 'تشریحی'), ('TrueFalse', 'درست/نادرست')], max_length=20, verbose_name='نوع سوال')),
                ('score', models.FloatField(verbose_name='نمره')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam.exam', verbose_name='آزمون')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوالات',
            },
        ),
        migrations.CreateModel(
            name='UserOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='نمره اختصاص داده\u200cشده')),
                ('answer_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.option', verbose_name='پاسخ داده شده')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam', verbose_name='آزمون')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.question', verbose_name='سوال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student', verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'پاسخ تستی دانش\u200cآموز',
                'verbose_name_plural': 'پاسخ\u200cهای تستی دانش\u200cآموزان',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(verbose_name='پاسخ داده\u200cشده')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='نمره اختصاص داده\u200cشده')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam', verbose_name='آزمون')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.question', verbose_name='سوال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student', verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'پاسخ دانش\u200cآموز',
                'verbose_name_plural': 'پاسخ\u200cهای دانش\u200cآموزان',
            },
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exam.question', verbose_name='سوال'),
        ),
    ]
