# Generated by Django 4.2.23 on 2025-07-04 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_customuser_is_team'),
        ('exam', '0006_remove_useroptions_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن بازخورد')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam', verbose_name='آزمون')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student', verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'بازخورد',
                'verbose_name_plural': 'بازخوردها',
            },
        ),
    ]
