# Generated by Django 4.2.23 on 2025-07-10 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0007_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='examcategory',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='exam_categories', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
