# Generated by Django 4.2.23 on 2025-07-10 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_examcategory_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='institute',
        ),
    ]
