# Generated by Django 4.2.23 on 2025-07-10 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_remove_classroom_institute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='exam',
        ),
    ]
