# Generated by Django 4.2.23 on 2025-07-10 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0010_remove_useranswer_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='سازنده آزمون'),
        ),
    ]
