# Generated by Django 4.2.23 on 2025-07-24 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_alter_exam_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useroptions',
            name='exam',
        ),
    ]
