# Generated by Django 4.2.23 on 2025-09-03 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_customuser_is_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0013_exam_result_show_time_alter_useranswer_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='core.teacher', verbose_name='استاد'),
        ),
        migrations.AlterField(
            model_name='examcategory',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentclassroom',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_classroom', to='exam.classroom', verbose_name='کلاس'),
        ),
        migrations.AlterField(
            model_name='studentclassroom',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_classroom', to='core.student', verbose_name='دانشجو'),
        ),
        migrations.AlterField(
            model_name='userexamresult',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam', verbose_name='آزمون'),
        ),
        migrations.CreateModel(
            name='UserExamTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع آزمون')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam', verbose_name='آزمون')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student', verbose_name='دانش آموز')),
            ],
            options={
                'verbose_name': 'زمان شروع آزمون دانشجو',
                'verbose_name_plural': 'زمان های شروع آزمون دانشجو',
            },
        ),
    ]
