# Generated by Django 4.2.23 on 2025-09-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_alter_classroom_teacher_alter_examcategory_creator_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userexamtime',
            options={'verbose_name': 'زمان پایان آزمون دانشجو', 'verbose_name_plural': 'زمان های پایان آزمون دانشجو'},
        ),
        migrations.RemoveField(
            model_name='userexamtime',
            name='start_time',
        ),
        migrations.AddField(
            model_name='userexamtime',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان آزمون'),
        ),
    ]
