# Generated by Django 4.2.23 on 2025-06-27 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customuser_email_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام آموزشگاه')),
                ('registration_code', models.CharField(max_length=50, unique=True, verbose_name='کد ثبت آموزشگاه')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('website', models.URLField(blank=True, null=True, verbose_name='وب\u200cسایت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='institute', to=settings.AUTH_USER_MODEL, verbose_name='حساب کاربری')),
            ],
            options={
                'verbose_name': 'آموزشگاه',
                'verbose_name_plural': 'آموزشگاه\u200cها',
            },
        ),
    ]
