# Generated by Django 4.2.23 on 2025-06-27 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_institute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_code', models.CharField(max_length=10, unique=True, verbose_name='کد ملی')),
                ('phone_number', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('expertise', models.CharField(max_length=100, verbose_name='تخصص')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='teacher', to=settings.AUTH_USER_MODEL, verbose_name='حساب کاربری')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='core.institute', verbose_name='آموزشگاه')),
            ],
            options={
                'verbose_name': 'استاد',
                'verbose_name_plural': 'اساتید',
            },
        ),
    ]
