# Generated by Django 4.2.23 on 2025-06-27 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_major_alter_classroom_grade_alter_classroom_teacher_and_more'),
        ('core', '0007_alter_teacher_account_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exam.major', verbose_name='رشته تحصیلی'),
        ),
    ]
