# Generated by Django 4.2.23 on 2025-06-27 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_student_major'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_team',
        ),
    ]
